### ISSUE TITLE
"Viewing Individual Contact" page does not display "Contact Instructions"

### ISSUE THREAD

**Issue by hmaier-fws** [adiwg/mdEditor#420]
## Issue
**mdEditor Version**: Version: 0.10.0+b30b3f9f
**mdEditor Web Address**: https://go.mdeditor.org/#/contact/<id>

### Issue Description:
The "Viewing Individual Contact" page does not display the information that was entered into the "Contact Instructions" field. Information can be entered into the "Contact Instructions" field when editing a contact. The information is retained and available on subsequent edit sessions, however, the text is not displayed on the "Viewing Individual Contact" summary page.

### Steps to reproduce (Bug reports only):
  1. Edit contact
  2. Enter information in "Contact Instructions" field
  3. Save edits
  4. Select a contact in the primary side bar to view contact details

### Observed Results (Bug reports only):
Contact details page displays "Not Defined" next to "Contact Instructions".

### Expected Results (Bug reports only):
Contact details page should display the text that is saved in the "Contact Instructions" field.

**Comment by dwalt** [comment]
This appears to have been resolved, closing issue.

**Comment by dwalt** [comment]
Done

**Comment by hmaier-fws** [comment]
@dwalt is this a browser-specific issue? I just tried it and it does not seem to be resolved when using Chrome. The `contact instructions` field is visible on the *contact edit page* (https:\/\/go.mdeditor.org\/#\/contact\/**contactID**\/**edit**). However, the information entered in that field still does not display when viewing the contact summary page (https:\/\/go.mdeditor.org\/#\/contact\/**contactID**)

**Comment by dwalt** [comment]
@hmaier-fws My bad, misinterpreted the report.
